Pull request for lab 2
catea016/PAM_application pull request #3
Opened 2021-03-09 11:54 UTC by catea016

2021-03-11 19:33 UTC, ASV44 approved these changes

2021-03-11 19:33 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/LoginActivity.kt
> +        sendButton = findViewById(R.id.sendButton)
Change init of activity view to android view binding https://developer.android.com/topic/libraries/view-binding

Also change access of view elements to view binding access

2021-03-11 19:33 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/WelcomeActivity.kt
> +        setContentView(R.layout.activity_welcome)
Change init of activity view to android view binding https://developer.android.com/topic/libraries/view-binding

2021-03-11 19:33 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/foodAndDrinks/FoodAdapter.kt
> +        val itemView = LayoutInflater.from(parent.context).inflate(R.layout.list_item_grid_food, parent, false)
Change init of recycler view items to android view binding https://developer.android.com/topic/libraries/view-binding

You can consult example from my sample repository.

2021-03-11 19:33 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/foodAndDrinks/FoodAdapter.kt
> +        var price: TextView = view.findViewById(R.id.textPrice)
Change access of view elements to android view binding

2021-03-11 19:33 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/foodAndDrinks/FoodModel.kt
> +        }
replace self written setter and getters with kotlin properties access https://kotlinlang.org/docs/properties.html

2021-03-11 19:33 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/foodAndDrinks/RecyclerActivity.kt
> +        setContentView(R.layout.activity_recycler)
Change init of activity view to android view binding https://developer.android.com/topic/libraries/view-binding

2021-03-11 19:34 UTC, ASV44 requested changes
@catea016 Please perform all changes from comments above and ping me when you will finish

2021-03-11 20:53 UTC, catea016 commented
@ASV44 eu am introdus schimbarile mentionate mai sus, dar cu setters si getters nu mi se primeste eu am comentat seterele scrise cu kotlin properties, deoarece cand incerc sa accesez functia get() in FoodAdapter, nu o citeste si nu stiu care e cauza

2021-03-11 21:27 UTC, ASV44 commented
> @ASV44 eu am introdus schimbarile mentionate mai sus, dar cu setters si getters nu mi se primeste eu am comentat seterele scrise cu kotlin properties, deoarece cand incerc sa accesez functia get() in FoodAdapter, nu o citeste si nu stiu care e cauza

@catea016  You have not to access variable by get function. Getter and setters in kotlin are just some decorators and if you add get or set function you can just access property by its name but the get or set function will be invoked.
Just write instead of `getVariableName()`, just `variableName` and everything will work.

2021-03-11 21:36 UTC, catea016 commented
@ASV44 thank you! All done

2021-03-11 21:59 UTC, ASV44 requested changes

2021-03-11 21:59 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/CategoryActivity.kt
> +
Remove empty lines

2021-03-11 21:59 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/WelcomeActivity.kt
> +    lateinit var login_button: Button*/
Remove commented code

2021-03-11 21:59 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/WelcomeActivity.kt
> +       // login_button = findViewById(R.id.loginButton)
Remove commented code

2021-03-11 21:59 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/foodAndDrinks/FoodModel.kt
> +        }
Change name of variable to image, name and price. There is no point to use such names as `setGet`

2021-03-12 07:17 UTC, catea016 commented
@ASV44 done

2021-03-12 12:28 UTC, ASV44 approved these changes
@catea016 PR approved. Feel free to merge it

2021-03-12 12:30 UTC, merged