Pull request for laboratory work nr 4
catea016/PAM_application pull request #6
Opened 2021-04-22 16:27 UTC by catea016

2021-04-23 20:26 UTC, ASV44 requested changes
Please merge previous PR and rebase this one

2021-04-24 13:58 UTC, catea016 commented
@ASV44  eu am facut rebase ce trebuie sa fac mai departe?

2021-04-24 16:15 UTC, catea016 commented
@ASV44  am facut rebase. Pot inchide pull request-ul?

2021-04-25 14:25 UTC, ASV44 requested changes
@catea016 You have conflicts after merging previous PR. Please rebase current branch on top of main. Push changes and ping me.

2021-04-25 14:30 UTC, catea016 commented
@ASV44 I did this yesterday https://github.com/catea016/PAM_application/tree/master/PAM_app/app/src/main/java/com/example/pam_app

2021-04-25 15:09 UTC, ASV44 commented
@catea016 you have conflicts. That means current branch is not on top of the main. You have to rebase current branch using `git rebase origin/master` command and to resolve conflicts during rebase. Please do it and force push rebased branch

2021-04-25 15:48 UTC, catea016 commented
@ASV44 I solved the conflicts

2021-04-25 21:26 UTC, ASV44 requested changes
@catea016 I also observed that in your `Model` class you perform calls to `Repository`. It is common practice to name as `Model` only plain objects which holds data. If you really need that `Model` class change it name to something else which reflects it behavior, like service, gateway or something else.
Also don't forget about abstraction between app modules.

2021-04-25 21:26 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/cosmetics/CosmeticsActivity.kt
> +            Toast.makeText(this, response.code().toString(), Toast.LENGTH_SHORT).show()
This is actually presentation business logic. It should be moved to presenter, in that way it could be covered with unit tests.

2021-04-25 21:26 UTC, ASV44 commented on PAM_app/app/src/main/java/com/example/pam_app/cosmetics/CosmeticsActivity.kt
> +    }
Same problem with presentation business logic here. Also don't use `Response` data type in Activities, use only plain models.

2021-05-19 09:58 UTC, ASV44 approved these changes
@catea016 PR approved. Feel free to merge it

2021-05-19 10:20 UTC, merged